# Site settings
title: martin disley
email: martin_disley@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  music and new media   
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: martin_disley
github_username:  martindisley

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/


